### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Viniciaao** [user-grinch/Map-Editor#7]
Crash at the very end of Game Load

CrashInfo https://pastebin.com/Pu7bysF1
ModLoader Log https://drive.google.com/file/d/10TskuhPMficE6OAUQR7qPYHyXZj0JTGl/view?usp=sharing
[MapEditorSA.log](https://github.com/user-grinch/Map-Editor/files/13064405/MapEditorSA.log)

**Comment by Anime-Guy2000** [comment]
Same issue.
